# Generated by Django 3.0.8 on 2020-07-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdrive', '0002_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfiles',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
