# Generated by Django 3.0.8 on 2020-07-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdrive', '0003_userfiles_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfiles',
            name='file_name',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
